#!/usr/bin/env ruby

def get_data()
    '700200040400030907015040000000700000057000210000009000000080360503070002020006004'
end

class Cell

    attr_reader :board, :row, :col, :possibles
    
    def initialize(board, row, col)
        @board = board
        @row = row
        @col = col
        @possibles = '123456789'
    end
    
    def box()
        (@row / 3) * 3 + (@col / 3)
    end
    
    def has?(possible)
        @possibles.length > 1 and @possibles.include? possible
    end
    
    def solve(value)
        @possibles = value
    end
    
    def remove(value)
        found = false
        if @possibles.length > 1
            found = @possibles.sub!(value, '')
            if @possibles.length == 1
                puts "#{self} solved"
                @board.solve(self, @possibles)
            end
        end
        found
    end
    
    def remove_possibles(values)
        found = false        
        values.scan(/./).each { |value| found ||= remove(value) }
        found
    end
    
    def to_s()
        "Cell #{@row}:#{@col}=#{@possibles}"
    end
    
end 

class Board

    def initialize(data)
        puts "=== Populating board ==="
        @cells = []
        (0..8).each { |row| (0..8).each { |col| @cells << Cell.new(self, row, col) }}
        i = 0
        (0..8).each { |row| (0..8).each { |col| 
            value = data[i,1]
            solve(cell(row, col), value) if value != '0' 
            i += 1
        }}
            
    end
    
    def to_s()
        s = []
        s << '=' * 50
        (0..8).each do |row|
            r = []
            cells_by_row(row).each { |cell| r << cell.possibles }
            s << "#{row}:[#{r.join(",")}]"
        end
        s << '=' * 50
        s.join("\n")
    end
    
    def solve(solved_cell, value)
        solved_cell.solve(value)
        @cells.each { |cell| cell.remove(value) if cell.row == solved_cell.row or cell.col == solved_cell.col or cell.box == solved_cell.box }
    end
    
    def cell(row, col)
        @cells[row * 9 + col]
    end
    
    def cells_by_row(row)
        @cells.select { |cell| cell.row == row }
    end

    def cells_by_col(col)
        @cells.select { |cell| cell.col == col }
    end

    def cells_by_box(box)
        @cells.select { |cell| cell.box == box }
    end
    
    def singles
        puts "=== Singles ==="
        found = false
        row = col = 0
        
        (0..8).each do |row|
            "123456789".scan(/./) do |possible|
                count = 0
                cells_by_row(row).each do |cell|
                    if cell.has?(possible)
                        count += 1
                        col = cell.col
                    end
                end
                if count == 1
                    puts "Single #{possible} in row #{row}"
                    solve(cell(row, col), possible)
                    found = true
                end
            end
        end
        
        (0..8).each do |col|
            "123456789".scan(/./) do |possible|
                count = 0
                cells_by_col(col).each do |cell|
                    if cell.has?(possible)
                        count += 1
                        row = cell.row
                    end
                end
                if count == 1
                    puts "Single #{possible} in col #{col}"
                    solve(cell(row, col), possible)
                    found = true
                end
            end
        end
        
        (0..8).each do |box|
            "123456789".scan(/./) do |possible|
                count = 0
                cells_by_box(box).each do |cell|
                    if cell.has?(possible)
                        count += 1
                        row = cell.row
                        col = cell.col
                    end
                end
                if count == 1
                    puts "Single #{possible} in box #{box}"
                    solve(cell(row, col), possible)
                    found = true
                end
            end
        end
        
        found
    end

    def naked_pairs
        puts "=== Naked Pairs ==="
        found = false
        row = col = 0
        
        (0..8).each do |row|
            pairs = cells_by_row(row).select { |cell| cell.possibles.length == 2}
            while pairs.length >= 2
                first = pairs.pop
                pairs.each do |second|
                    if first.possibles == second.possibles
                        cells_by_row(row).each do |cell|
                            if cell != first and cell != second and cell.remove_possibles(first.possibles)
                                puts "Naked Pair #{first.possibles} on row #{row}"
                                found = true
                            end
                        end
                    end
                end
            end
        end
        
        (0..8).each do |col|
            pairs = cells_by_col(col).select { |cell| cell.possibles.length == 2}
            while pairs.length >= 2
                first = pairs.pop
                pairs.each do |second|
                    if first.possibles == second.possibles
                        cells_by_col(col).each do |cell|
                            if cell != first and cell != second and cell.remove_possibles(first.possibles)
                                puts "Naked Pair #{first.possibles} on col #{col}"
                                found = true
                            end
                        end
                    end
                end
            end
        end
        
        (0..8).each do |box|
            pairs = cells_by_box(box).select { |cell| cell.possibles.length == 2}
            while pairs.length >= 2
                first = pairs.pop
                pairs.each do |second|
                    if first.possibles == second.possibles
                        cells_by_box(box).each do |cell|
                            if cell != first and cell != second and cell.remove_possibles(first.possibles)
                                puts "Naked Pair #{first.possibles} on box #{box}"
                                found = true
                            end
                        end
                    end
                end
            end
        end
        
        found        
    end
        
    def pointing_pairs
        puts "=== Pointing Pairs ==="
        found = false
        row = col = 0
        
        (0..8).each do |box|
            "123456789".scan(/./).each do |possible|
                pairs = cells_by_box(box).select { |cell| cell.has? possible}
                if pairs.length == 2 or pairs.length == 3
                    if pairs[0].row == pairs[1].row and pairs[0].row == pairs[-1].row
                        cells_by_row(pairs[0].row).each do |cell| 
                            if not pairs.include? cell and cell.remove(possible) 
                                found = true
                            end
                        end
                    end
                    if pairs[0].col == pairs[1].col and pairs[0].col == pairs[-1].col
                        cells_by_col(pairs[0].col).each do |cell| 
                            if not pairs.include? cell and cell.remove(possible) 
                                found = true
                            end
                        end
                    end
                end
                if found
                    puts "Pointing Pair #{possible} on box #{box}"
                    return true
                end
            end
        end
        
        found        
    end
        
end

board = Board.new(get_data)
running = true
while running
    if board.singles
    elsif board.naked_pairs
    elsif board.pointing_pairs
    else 
        running = false
    end
    puts board.to_s
end


